# Generated by Django 2.1.7 on 2019-10-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_veri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=7)),
                ('tran_id', models.CharField(max_length=30)),
                ('verified', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
    ]
